import path from 'path';
import fs from 'fs';
import chalk from 'chalk';
import { confirm } from '@inquirer/prompts';
import YAML from 'yaml';
import {
    HERMES_PLUGIN_DIR,
    HERMES_CONFIG_PATH,
    MARKET_NAME,
} from '@/_defs';
import { configManager } from '@/_libs/config';
import { resolveRepoPath } from '@/_libs';

const PLUGIN_YAML = `name: ${MARKET_NAME}
version: "1.0"
description: Managed by set-prompt
`;

// Reads skills/commands/hooks directly from the set-prompt repo at startup.
// No symlinks: the repo path is baked into REPO_DIR at link time.
// - Skills: registered via ctx.register_skill() from <repo>/skills/.
// - Commands: <repo>/commands/*.md → slash commands that inject the body as a user message.
// - Hooks: <repo>/hooks/hooks.json (shared with Claude Code/Cursor). Only Hermes-native
//   event keys are picked up; other tools' keys are ignored.
const buildInitPy = (repoPath: string): string => {
    const repoLiteral = JSON.stringify(repoPath);
    return `"""Auto-generated by set-prompt. Do not edit by hand."""
import json
import os
import subprocess
from pathlib import Path

REPO_DIR = Path(${repoLiteral})

HERMES_EVENTS = {
    "pre_tool_call",
    "post_tool_call",
    "pre_llm_call",
    "post_llm_call",
    "on_session_start",
    "on_session_end",
    "on_session_finalize",
    "on_session_reset",
    "subagent_stop",
    "pre_gateway_dispatch",
}


def _parse_frontmatter(text):
    if not text.startswith("---"):
        return {}, text
    end = text.find("\\n---", 3)
    if end == -1:
        return {}, text
    meta_block = text[3:end].strip()
    body = text[end + 4:].lstrip("\\n")
    meta = {}
    for line in meta_block.splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        meta[key.strip()] = value.strip().strip('"').strip("'")
    return meta, body


def _make_command_handler(ctx, body):
    # Hermes calls handlers as handler(raw_args: str) -> Optional[str].
    # Primary path: inject the markdown body as a user message (CLI mode).
    # Fallback: in gateway mode inject_message returns False — return the body
    # as the handler response so the content is at least visible to the user.
    def handler(raw_args=""):
        try:
            ok = ctx.inject_message(body, role="user")
        except Exception:
            ok = False
        if not ok:
            return body
        return None
    return handler


def _make_hook_runner(event, raw_cmd, timeout):
    def runner(*args, **kwargs):
        cmd = raw_cmd.replace("\${SET_PROMPT_REPO}", str(REPO_DIR))
        env = dict(os.environ)
        env["SET_PROMPT_REPO"] = str(REPO_DIR)
        payload = json.dumps({
            "event": event,
            "args": [repr(a) for a in args],
            "kwargs": {k: repr(v) for k, v in kwargs.items()},
        }).encode("utf-8")
        try:
            subprocess.run(
                cmd, shell=True, input=payload, env=env,
                timeout=timeout if isinstance(timeout, (int, float)) else None,
                check=False,
            )
        except (subprocess.TimeoutExpired, OSError):
            pass
    return runner


def _iter_hook_commands(entries):
    if not isinstance(entries, list):
        return
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        sub = entry.get("hooks")
        if not isinstance(sub, list):
            continue
        for h in sub:
            if not isinstance(h, dict):
                continue
            if h.get("type") != "command":
                continue
            cmd = h.get("command")
            if not isinstance(cmd, str) or not cmd:
                continue
            yield cmd, h.get("timeout")


def _register_hooks(ctx):
    hooks_json = REPO_DIR / "hooks" / "hooks.json"
    if not hooks_json.exists():
        return
    try:
        data = json.loads(hooks_json.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return
    block = data.get("hooks") if isinstance(data, dict) else None
    if not isinstance(block, dict):
        return
    for event, entries in block.items():
        if event not in HERMES_EVENTS:
            continue
        for cmd, timeout in _iter_hook_commands(entries):
            ctx.register_hook(event, _make_hook_runner(event, cmd, timeout))


def register(ctx):
    skills_dir = REPO_DIR / "skills"
    if skills_dir.exists():
        for skill_path in sorted(skills_dir.iterdir()):
            if not skill_path.is_dir():
                continue
            skill_md = skill_path / "SKILL.md"
            if not skill_md.exists():
                continue
            # Hermes expects (name, Path-to-SKILL.md), not (name, dir-as-str).
            ctx.register_skill(skill_path.name, skill_md)

    commands_dir = REPO_DIR / "commands"
    if commands_dir.exists():
        for cmd_file in sorted(commands_dir.glob("*.md")):
            try:
                text = cmd_file.read_text(encoding="utf-8")
            except OSError:
                continue
            meta, body = _parse_frontmatter(text)
            name = meta.get("name") or cmd_file.stem
            description = meta.get("description") or ""
            ctx.register_command(
                name,
                handler=_make_command_handler(ctx, body),
                description=description,
            )

    _register_hooks(ctx)
`;
};

const FRESH_CONFIG_YAML = `# Generated by set-prompt
plugins:
  enabled:
    - ${MARKET_NAME}
`;

const writePluginManifest = (repoPath: string): void => {
    fs.writeFileSync(path.join(HERMES_PLUGIN_DIR, 'plugin.yaml'), PLUGIN_YAML, 'utf-8');
    fs.writeFileSync(path.join(HERMES_PLUGIN_DIR, '__init__.py'), buildInitPy(repoPath), 'utf-8');
};

// Atomic write helper: creates a timestamped backup, writes, and rolls back on failure.
const writeWithBackup = (filePath: string, content: string): void => {
    let backupPath: string | null = null;
    if (fs.existsSync(filePath)) {
        const timestamp = new Date().toISOString().replace(/[:.]/g, '-');
        backupPath = `${filePath}.bak.${timestamp}`;
        try {
            fs.copyFileSync(filePath, backupPath);
        } catch {
            backupPath = null;
        }
    }

    try {
        fs.mkdirSync(path.dirname(filePath), { recursive: true });
        fs.writeFileSync(filePath, content, 'utf-8');
    } catch (ex) {
        if (backupPath !== null) {
            try {
                fs.copyFileSync(backupPath, filePath);
                fs.unlinkSync(backupPath);
                console.warn(chalk.yellow('  ⚠ Write failed — rolled back to original.'));
            } catch {
                console.error(chalk.red(`  ❌ Rollback failed. Backup preserved at: ${backupPath}`));
            }
        }
        throw ex;
    }

    if (backupPath !== null) {
        try { fs.unlinkSync(backupPath); } catch { /* ignore */ }
    }
};

const ensureHermesConfigEnabled = (): void => {
    if (fs.existsSync(HERMES_CONFIG_PATH) === false) {
        fs.mkdirSync(path.dirname(HERMES_CONFIG_PATH), { recursive: true });
        fs.writeFileSync(HERMES_CONFIG_PATH, FRESH_CONFIG_YAML, 'utf-8');
        console.log(chalk.green('  ✓ ') + chalk.dim(`wrote ${HERMES_CONFIG_PATH}`));
        return;
    }

    const content = fs.readFileSync(HERMES_CONFIG_PATH, 'utf-8');
    let doc: YAML.Document.Parsed;
    try {
        doc = YAML.parseDocument(content);
    } catch (ex: any) {
        console.warn(chalk.yellow(`  ⚠ Failed to parse Hermes config (${ex.message}) — leaving file untouched.`));
        console.log(chalk.dim(`    File: ${HERMES_CONFIG_PATH}`));
        return;
    }

    if (doc.errors.length > 0) {
        console.warn(chalk.yellow(`  ⚠ Hermes config has YAML errors — leaving file untouched.`));
        console.log(chalk.dim(`    File: ${HERMES_CONFIG_PATH}`));
        return;
    }

    // Ensure plugins is a map.
    let plugins = doc.get('plugins');
    if (plugins == null) {
        doc.set('plugins', doc.createNode({ enabled: [MARKET_NAME] }));
        writeWithBackup(HERMES_CONFIG_PATH, String(doc));
        console.log(chalk.green('  ✓ ') + chalk.dim(`added plugins.enabled to ${HERMES_CONFIG_PATH}`));
        return;
    }

    if (!YAML.isMap(plugins)) {
        console.warn(chalk.yellow(`  ⚠ "plugins" is not a map — leaving file untouched.`));
        console.log(chalk.dim(`    File: ${HERMES_CONFIG_PATH}`));
        return;
    }

    let enabled = plugins.get('enabled');
    if (enabled == null) {
        plugins.set('enabled', doc.createNode([MARKET_NAME]));
        writeWithBackup(HERMES_CONFIG_PATH, String(doc));
        console.log(chalk.green('  ✓ ') + chalk.dim(`added plugins.enabled to ${HERMES_CONFIG_PATH}`));
        return;
    }

    if (!YAML.isSeq(enabled)) {
        console.warn(chalk.yellow(`  ⚠ "plugins.enabled" is not a list — leaving file untouched.`));
        console.log(chalk.dim(`    File: ${HERMES_CONFIG_PATH}`));
        return;
    }

    const alreadyListed = enabled.items.some((item) => {
        const v = YAML.isScalar(item) ? item.value : item;
        return v === MARKET_NAME;
    });
    if (alreadyListed) {
        console.log(chalk.dim(`  ✓ ${MARKET_NAME} already listed in ${HERMES_CONFIG_PATH}`));
        return;
    }

    enabled.add(MARKET_NAME);
    writeWithBackup(HERMES_CONFIG_PATH, String(doc));
    console.log(chalk.green('  ✓ ') + chalk.dim(`enabled "${MARKET_NAME}" in ${HERMES_CONFIG_PATH}`));
};

export const linkHermes = async (): Promise<void> => {
    const repoPath = resolveRepoPath();
    if (repoPath == null) { return; }

    console.log(chalk.green(`\nSetting up Hermes plugin...`));
    console.log(chalk.dim(HERMES_PLUGIN_DIR));

    try {
        fs.mkdirSync(HERMES_PLUGIN_DIR, { recursive: true });

        writePluginManifest(repoPath);
        console.log(chalk.dim('  ├── ') + chalk.bold('plugin.yaml') + chalk.green(' ✓'));
        console.log(chalk.dim('  └── ') + chalk.bold('__init__.py') + chalk.dim(` (REPO_DIR → ${repoPath})`) + chalk.green(' ✓'));

        ensureHermesConfigEnabled();

        configManager.hermes = { path: HERMES_PLUGIN_DIR };
        configManager.save();

        console.log(chalk.dim(`\n  ℹ Hermes loads plugins at startup — restart Hermes to pick up new skills/commands.`));
    } catch (ex: any) {
        console.error(chalk.red(`❌ Failed to set up Hermes plugin: ${ex.message}`));
    }
};

export const unlinkHermes = async (force = false): Promise<void> => {
    if (!force) {
        const ok = await confirm({
            message: `Remove Hermes plugin dir (${HERMES_PLUGIN_DIR})?`,
            default: false,
        });
        if (!ok) { console.log(chalk.yellow('Cancelled.')); return; }
    }

    console.log(chalk.red(`\nRemoving Hermes plugin...`));
    console.log(chalk.dim(HERMES_PLUGIN_DIR));

    if (fs.existsSync(HERMES_PLUGIN_DIR)) {
        fs.rmSync(HERMES_PLUGIN_DIR, { recursive: true, force: true });
        console.log(chalk.red('  removed') + chalk.dim(`: ${HERMES_PLUGIN_DIR}`));
    }

    if (fs.existsSync(HERMES_CONFIG_PATH)) {
        const content = fs.readFileSync(HERMES_CONFIG_PATH, 'utf-8');
        if (content.trimStart().startsWith('# Generated by set-prompt')) {
            fs.unlinkSync(HERMES_CONFIG_PATH);
            console.log(chalk.red('  removed') + chalk.dim(`: ${HERMES_CONFIG_PATH}`));
        } else {
            removeMarketEntryFromConfig();
        }
    }

    configManager.hermes = null;
    configManager.save();
};

const removeMarketEntryFromConfig = (): void => {
    const content = fs.readFileSync(HERMES_CONFIG_PATH, 'utf-8');
    let doc: YAML.Document.Parsed;
    try {
        doc = YAML.parseDocument(content);
    } catch (ex: any) {
        console.warn(chalk.yellow(`  ⚠ Failed to parse Hermes config (${ex.message}) — leaving file untouched.`));
        return;
    }
    if (doc.errors.length > 0) { return; }

    const plugins = doc.get('plugins');
    if (!YAML.isMap(plugins)) { return; }
    const enabled = plugins.get('enabled');
    if (!YAML.isSeq(enabled)) { return; }

    const idx = enabled.items.findIndex((item) => {
        const v = YAML.isScalar(item) ? item.value : item;
        return v === MARKET_NAME;
    });
    if (idx === -1) { return; }

    enabled.delete(idx);
    writeWithBackup(HERMES_CONFIG_PATH, String(doc));
    console.log(chalk.red('  removed') + chalk.dim(` "${MARKET_NAME}" from: ${HERMES_CONFIG_PATH}`));
};
