import path from 'path';
import fs from 'fs';
import chalk from 'chalk';
import { confirm } from '@inquirer/prompts';
import {
    HERMES_PLUGIN_DIR,
    HERMES_CONFIG_PATH,
    MARKET_NAME,
} from '@/_defs';
import { configManager } from '@/_libs/config';
import { resolveRepoPath } from '@/_libs';

const PLUGIN_YAML = `name: ${MARKET_NAME}
version: "1.0"
description: Managed by set-prompt
`;

// Reads skills/commands/hooks directly from the set-prompt repo at startup.
// No symlinks: the repo path is baked into REPO_DIR at link time.
// - Skills: registered via ctx.register_skill() from <repo>/skills/.
// - Commands: <repo>/commands/*.md → slash commands that inject the body as a user message.
// - Hooks: <repo>/hooks/hooks.json (shared with Claude Code/Cursor). Only Hermes-native
//   event keys are picked up; other tools' keys are ignored.
const buildInitPy = (repoPath: string): string => {
    const repoLiteral = JSON.stringify(repoPath);
    return `"""Auto-generated by set-prompt. Do not edit by hand."""
import json
import os
import subprocess
from pathlib import Path

REPO_DIR = Path(${repoLiteral})

HERMES_EVENTS = {
    "pre_tool_call",
    "post_tool_call",
    "pre_llm_call",
    "post_llm_call",
    "on_session_start",
    "on_session_end",
    "on_session_finalize",
    "on_session_reset",
    "subagent_stop",
    "pre_gateway_dispatch",
}


def _parse_frontmatter(text):
    if not text.startswith("---"):
        return {}, text
    end = text.find("\\n---", 3)
    if end == -1:
        return {}, text
    meta_block = text[3:end].strip()
    body = text[end + 4:].lstrip("\\n")
    meta = {}
    for line in meta_block.splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        meta[key.strip()] = value.strip().strip('"').strip("'")
    return meta, body


def _make_command_handler(ctx, body):
    def handler(_args=None):
        ctx.inject_message(body, role="user")
    return handler


def _make_hook_runner(event, raw_cmd, timeout):
    def runner(*args, **kwargs):
        cmd = raw_cmd.replace("\${SET_PROMPT_REPO}", str(REPO_DIR))
        env = dict(os.environ)
        env["SET_PROMPT_REPO"] = str(REPO_DIR)
        payload = json.dumps({
            "event": event,
            "args": [repr(a) for a in args],
            "kwargs": {k: repr(v) for k, v in kwargs.items()},
        }).encode("utf-8")
        try:
            subprocess.run(
                cmd, shell=True, input=payload, env=env,
                timeout=timeout if isinstance(timeout, (int, float)) else None,
                check=False,
            )
        except (subprocess.TimeoutExpired, OSError):
            pass
    return runner


def _iter_hook_commands(entries):
    if not isinstance(entries, list):
        return
    for entry in entries:
        if not isinstance(entry, dict):
            continue
        sub = entry.get("hooks")
        if not isinstance(sub, list):
            continue
        for h in sub:
            if not isinstance(h, dict):
                continue
            if h.get("type") != "command":
                continue
            cmd = h.get("command")
            if not isinstance(cmd, str) or not cmd:
                continue
            yield cmd, h.get("timeout")


def _register_hooks(ctx):
    hooks_json = REPO_DIR / "hooks" / "hooks.json"
    if not hooks_json.exists():
        return
    try:
        data = json.loads(hooks_json.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return
    block = data.get("hooks") if isinstance(data, dict) else None
    if not isinstance(block, dict):
        return
    for event, entries in block.items():
        if event not in HERMES_EVENTS:
            continue
        for cmd, timeout in _iter_hook_commands(entries):
            ctx.register_hook(event, _make_hook_runner(event, cmd, timeout))


def register(ctx):
    skills_dir = REPO_DIR / "skills"
    if skills_dir.exists():
        for skill_path in sorted(skills_dir.iterdir()):
            if not skill_path.is_dir():
                continue
            if not (skill_path / "SKILL.md").exists():
                continue
            ctx.register_skill(skill_path.name, str(skill_path))

    commands_dir = REPO_DIR / "commands"
    if commands_dir.exists():
        for cmd_file in sorted(commands_dir.glob("*.md")):
            try:
                text = cmd_file.read_text(encoding="utf-8")
            except OSError:
                continue
            meta, body = _parse_frontmatter(text)
            name = meta.get("name") or cmd_file.stem
            description = meta.get("description") or ""
            ctx.register_command(name, _make_command_handler(ctx, body), description)

    _register_hooks(ctx)
`;
};

const FRESH_CONFIG_YAML = `# Generated by set-prompt
plugins:
  enabled:
    - ${MARKET_NAME}
`;

const ENABLE_SNIPPET = `plugins:
  enabled:
    - ${MARKET_NAME}`;

const writePluginManifest = (repoPath: string): void => {
    fs.writeFileSync(path.join(HERMES_PLUGIN_DIR, 'plugin.yaml'), PLUGIN_YAML, 'utf-8');
    fs.writeFileSync(path.join(HERMES_PLUGIN_DIR, '__init__.py'), buildInitPy(repoPath), 'utf-8');
};

const ensureHermesConfigEnabled = (): void => {
    if (fs.existsSync(HERMES_CONFIG_PATH) === false) {
        fs.mkdirSync(path.dirname(HERMES_CONFIG_PATH), { recursive: true });
        fs.writeFileSync(HERMES_CONFIG_PATH, FRESH_CONFIG_YAML, 'utf-8');
        console.log(chalk.green('  ✓ ') + chalk.dim(`wrote ${HERMES_CONFIG_PATH}`));
        return;
    }

    const content = fs.readFileSync(HERMES_CONFIG_PATH, 'utf-8');
    // Conservative match: an "- set-prompt" entry under any list.
    const enabledPattern = new RegExp(`^\\s*-\\s+${MARKET_NAME}\\s*$`, 'm');
    if (enabledPattern.test(content)) {
        console.log(chalk.dim(`  ✓ ${MARKET_NAME} already listed in ${HERMES_CONFIG_PATH}`));
        return;
    }

    console.log(chalk.yellow(`\n  ⚠ Hermes config exists but does not list "${MARKET_NAME}" as enabled.`));
    console.log(chalk.dim('    Add the following entry under plugins.enabled to activate this plugin:\n'));
    console.log(chalk.cyan(ENABLE_SNIPPET.split('\n').map(l => `      ${l}`).join('\n')));
    console.log(chalk.dim(`\n    File: ${HERMES_CONFIG_PATH}`));
};

export const linkHermes = async (): Promise<void> => {
    const repoPath = resolveRepoPath();
    if (repoPath == null) { return; }

    console.log(chalk.green(`\nSetting up Hermes plugin...`));
    console.log(chalk.dim(HERMES_PLUGIN_DIR));

    try {
        fs.mkdirSync(HERMES_PLUGIN_DIR, { recursive: true });

        writePluginManifest(repoPath);
        console.log(chalk.dim('  ├── ') + chalk.bold('plugin.yaml') + chalk.green(' ✓'));
        console.log(chalk.dim('  └── ') + chalk.bold('__init__.py') + chalk.dim(` (REPO_DIR → ${repoPath})`) + chalk.green(' ✓'));

        ensureHermesConfigEnabled();

        configManager.hermes = { path: HERMES_PLUGIN_DIR };
        configManager.save();

        console.log(chalk.dim(`\n  ℹ Hermes loads plugins at startup — restart Hermes to pick up new skills/commands.`));
    } catch (ex: any) {
        console.error(chalk.red(`❌ Failed to set up Hermes plugin: ${ex.message}`));
    }
};

export const unlinkHermes = async (force = false): Promise<void> => {
    if (!force) {
        const ok = await confirm({
            message: `Remove Hermes plugin dir (${HERMES_PLUGIN_DIR})?`,
            default: false,
        });
        if (!ok) { console.log(chalk.yellow('Cancelled.')); return; }
    }

    console.log(chalk.red(`\nRemoving Hermes plugin...`));
    console.log(chalk.dim(HERMES_PLUGIN_DIR));

    if (fs.existsSync(HERMES_PLUGIN_DIR)) {
        fs.rmSync(HERMES_PLUGIN_DIR, { recursive: true, force: true });
        console.log(chalk.red('  removed') + chalk.dim(`: ${HERMES_PLUGIN_DIR}`));
    }

    if (fs.existsSync(HERMES_CONFIG_PATH)) {
        const content = fs.readFileSync(HERMES_CONFIG_PATH, 'utf-8');
        if (content.trimStart().startsWith('# Generated by set-prompt')) {
            fs.unlinkSync(HERMES_CONFIG_PATH);
            console.log(chalk.red('  removed') + chalk.dim(`: ${HERMES_CONFIG_PATH}`));
        } else if (new RegExp(`^\\s*-\\s+${MARKET_NAME}\\s*$`, 'm').test(content)) {
            console.log(chalk.yellow(`  ⚠ Hermes config still lists "${MARKET_NAME}" — remove it manually:`));
            console.log(chalk.dim(`    ${HERMES_CONFIG_PATH}`));
        }
    }

    configManager.hermes = null;
    configManager.save();
};
