import { describe, it, expect, beforeEach, vi } from 'vitest';
import { vol } from 'memfs';
import path from 'path';
import { HERMES_PLUGIN_DIR, HERMES_CONFIG_PATH, MARKET_NAME, PLUGIN_NAME } from '@/_defs';

vi.mock('fs', async () => {
    const { fs } = await import('memfs');
    return { default: fs, ...fs };
});

vi.mock('@inquirer/prompts', () => ({
    confirm: vi.fn(),
}));

vi.mock('@/_libs/config', () => ({
    configManager: {
        repo_path: null,
        hermes: null,
        save: vi.fn(),
    }
}));

const { linkHermes, unlinkHermes } = await import('@/link/hermes');
const { configManager } = await import('@/_libs/config');
const { confirm } = await import('@inquirer/prompts');

describe('linkHermes', () => {
    beforeEach(() => {
        vol.reset();
        vi.clearAllMocks();
        vi.mocked(configManager.save).mockReturnValue(true);
    });

    it('repo_path 미설정 → HERMES_PLUGIN_DIR 미생성', async () => {
        configManager.repo_path = null;
        await linkHermes();
        expect(vol.existsSync(HERMES_PLUGIN_DIR)).toBe(false);
    });

    it('repo_path 설정 → plugin.yaml과 __init__.py 생성', async () => {
        configManager.repo_path = '/fake/repo';

        await linkHermes();

        const yaml = vol.readFileSync(path.join(HERMES_PLUGIN_DIR, 'plugin.yaml'), 'utf-8') as string;
        const initPy = vol.readFileSync(path.join(HERMES_PLUGIN_DIR, '__init__.py'), 'utf-8') as string;
        expect(yaml).toContain(`name: ${PLUGIN_NAME}`);
        expect(initPy).toContain('def register(ctx)');
        expect(initPy).toContain('register_skill');
        expect(initPy).toContain('register_command');
        expect(initPy).toContain('register_hook');
        expect(initPy).toContain('HERMES_EVENTS');
        expect(initPy).toContain('pre_tool_call');
        expect(initPy).toContain('${SET_PROMPT_REPO}');
    });

    it('__init__.py에 REPO_DIR이 repo_path로 박혀있음', async () => {
        const repoPath = '/fake/repo';
        configManager.repo_path = repoPath;

        await linkHermes();

        const initPy = vol.readFileSync(path.join(HERMES_PLUGIN_DIR, '__init__.py'), 'utf-8') as string;
        expect(initPy).toContain(`REPO_DIR = Path("${repoPath}")`);
    });

    it('Windows 백슬래시 경로 → JSON 인코딩으로 안전하게 박힘', async () => {
        const repoPath = 'C:\\Users\\me\\.set-prompt\\repo';
        configManager.repo_path = repoPath;

        await linkHermes();

        const initPy = vol.readFileSync(path.join(HERMES_PLUGIN_DIR, '__init__.py'), 'utf-8') as string;
        expect(initPy).toContain('REPO_DIR = Path("C:\\\\Users\\\\me\\\\.set-prompt\\\\repo")');
    });

    it('symlink을 생성하지 않음 (직접 참조 방식)', async () => {
        configManager.repo_path = '/fake/repo';

        await linkHermes();

        expect(vol.existsSync(path.join(HERMES_PLUGIN_DIR, 'skills'))).toBe(false);
        expect(vol.existsSync(path.join(HERMES_PLUGIN_DIR, 'commands'))).toBe(false);
        expect(vol.existsSync(path.join(HERMES_PLUGIN_DIR, 'hooks'))).toBe(false);
    });

    it('config.yaml 부재 → set-prompt를 enabled로 자동 생성', async () => {
        configManager.repo_path = '/fake/repo';

        await linkHermes();

        const yaml = vol.readFileSync(HERMES_CONFIG_PATH, 'utf-8') as string;
        expect(yaml).toContain('# Generated by set-prompt');
        expect(yaml).toContain(`- ${PLUGIN_NAME}`);
    });

    it('config.yaml 존재 + set-prompt 이미 enabled → 파일 보존', async () => {
        configManager.repo_path = '/fake/repo';
        const original = `plugins:\n  enabled:\n    - ${PLUGIN_NAME}\n    - other\n`;
        vol.mkdirSync(path.dirname(HERMES_CONFIG_PATH), { recursive: true });
        vol.writeFileSync(HERMES_CONFIG_PATH, original);

        await linkHermes();

        const after = vol.readFileSync(HERMES_CONFIG_PATH, 'utf-8') as string;
        expect(after).toBe(original);
    });

    it('config.yaml 존재 + set-prompt 미포함 → set-prompt 자동 추가 + 다른 항목 보존', async () => {
        configManager.repo_path = '/fake/repo';
        const original = 'plugins:\n  enabled:\n    - other\n';
        vol.mkdirSync(path.dirname(HERMES_CONFIG_PATH), { recursive: true });
        vol.writeFileSync(HERMES_CONFIG_PATH, original);

        await linkHermes();

        const after = vol.readFileSync(HERMES_CONFIG_PATH, 'utf-8') as string;
        expect(after).toContain('- other');
        expect(after).toContain(`- ${PLUGIN_NAME}`);
    });

    it('config.yaml 존재 + plugins 키 없음 → plugins.enabled 추가', async () => {
        configManager.repo_path = '/fake/repo';
        const original = 'other_section:\n  foo: bar\n';
        vol.mkdirSync(path.dirname(HERMES_CONFIG_PATH), { recursive: true });
        vol.writeFileSync(HERMES_CONFIG_PATH, original);

        await linkHermes();

        const after = vol.readFileSync(HERMES_CONFIG_PATH, 'utf-8') as string;
        expect(after).toContain('foo: bar');
        expect(after).toContain('plugins:');
        expect(after).toContain(`- ${PLUGIN_NAME}`);
    });

    it('config.yaml 존재 + plugins.enabled 키 없음 → enabled 추가', async () => {
        configManager.repo_path = '/fake/repo';
        const original = 'plugins:\n  disabled:\n    - other\n';
        vol.mkdirSync(path.dirname(HERMES_CONFIG_PATH), { recursive: true });
        vol.writeFileSync(HERMES_CONFIG_PATH, original);

        await linkHermes();

        const after = vol.readFileSync(HERMES_CONFIG_PATH, 'utf-8') as string;
        expect(after).toContain('- other');
        expect(after).toContain('enabled:');
        expect(after).toContain(`- ${PLUGIN_NAME}`);
    });

    it('config.yaml 코멘트 보존 (yaml 라이브러리 사용)', async () => {
        configManager.repo_path = '/fake/repo';
        const original = '# my custom config\nplugins:\n  enabled:\n    - other\n';
        vol.mkdirSync(path.dirname(HERMES_CONFIG_PATH), { recursive: true });
        vol.writeFileSync(HERMES_CONFIG_PATH, original);

        await linkHermes();

        const after = vol.readFileSync(HERMES_CONFIG_PATH, 'utf-8') as string;
        expect(after).toContain('# my custom config');
        expect(after).toContain(`- ${PLUGIN_NAME}`);
    });

    it('성공 시 configManager.hermes에 path 저장', async () => {
        configManager.repo_path = '/fake/repo';
        await linkHermes();
        expect(configManager.hermes).toEqual({ path: HERMES_PLUGIN_DIR });
        expect(configManager.save).toHaveBeenCalled();
    });
});

describe('unlinkHermes', () => {
    beforeEach(() => {
        vol.reset();
        vi.clearAllMocks();
        configManager.hermes = null;
        vi.mocked(configManager.save).mockReturnValue(true);
    });

    it('force=true → confirm 없이 플러그인 디렉토리 제거', async () => {
        vol.mkdirSync(HERMES_PLUGIN_DIR, { recursive: true });
        vol.writeFileSync(path.join(HERMES_PLUGIN_DIR, 'plugin.yaml'), 'x');

        await unlinkHermes(true);

        expect(confirm).not.toHaveBeenCalled();
        expect(vol.existsSync(HERMES_PLUGIN_DIR)).toBe(false);
    });

    it('자동 생성된 config.yaml(헤더 포함) → 함께 삭제', async () => {
        vol.mkdirSync(HERMES_PLUGIN_DIR, { recursive: true });
        vol.writeFileSync(HERMES_CONFIG_PATH, `# Generated by set-prompt\nplugins:\n  enabled:\n    - ${PLUGIN_NAME}\n`);

        await unlinkHermes(true);

        expect(vol.existsSync(HERMES_CONFIG_PATH)).toBe(false);
    });

    it('사용자 작성 config.yaml(헤더 없음) → 파일 보존, set-prompt 엔트리만 제거', async () => {
        vol.mkdirSync(HERMES_PLUGIN_DIR, { recursive: true });
        const userConfig = `plugins:\n  enabled:\n    - ${PLUGIN_NAME}\n    - other\n`;
        vol.writeFileSync(HERMES_CONFIG_PATH, userConfig);

        await unlinkHermes(true);

        expect(vol.existsSync(HERMES_CONFIG_PATH)).toBe(true);
        const after = vol.readFileSync(HERMES_CONFIG_PATH, 'utf-8') as string;
        expect(after).not.toContain(`- ${PLUGIN_NAME}`);
        expect(after).not.toContain(`- ${MARKET_NAME}`);
        expect(after).toContain('- other');
    });

    it('사용자 작성 config.yaml에 set-prompt 미포함 → 파일 그대로 보존', async () => {
        vol.mkdirSync(HERMES_PLUGIN_DIR, { recursive: true });
        const userConfig = `plugins:\n  enabled:\n    - other\n`;
        vol.writeFileSync(HERMES_CONFIG_PATH, userConfig);

        await unlinkHermes(true);

        expect(vol.existsSync(HERMES_CONFIG_PATH)).toBe(true);
        expect(vol.readFileSync(HERMES_CONFIG_PATH, 'utf-8') as string).toBe(userConfig);
    });

    it('성공 시 configManager.hermes = null, save 호출', async () => {
        await unlinkHermes(true);
        expect(configManager.hermes).toBeNull();
        expect(configManager.save).toHaveBeenCalled();
    });
});
